language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install
before_script:
  - npm install -g dredd
script:
  - grunt 
  - ./test 
notifications:
  email:
    - jeffhann@gmail.com
